# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

image: gajesh/build-tools:latest

# List of stages for jobs, and their order of execution
stages:
  - ver
  - init
  - test
  - deploy

ver:
  stage: ver
  script:
    - python --version
    - whoami

init:
  stage: init
  script:
    - pip install -r requirements.txt

run_tests:
  stage: tests
  script:
    - pip install -r requirements.txt
    - python -m unittest api/tests.py

deploy_staging:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/hatchways-staging.git
    - git push heroku master
    - echo "Deployed to Staging Server https://hatchways-staging.herokuapp.com"
  environment:
    name: staging
    url: https://hatchways-staging.herokuapp.com
  only:
    - master

deploy_production:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/hatchways-production.git
    - git push heroku master
    - echo "Deployed Production Server https://hatchways-production.herokuapp.com"
  environment:
    name: production
    url : https://hatchways-production.herokuapp.com
  when: manual
  only:
    - master